api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    # pour enlever le hydra, la form application + ld /json
    formats:
        json: ['application/json']